name: Update Latest Repository

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get latest repo
        env:
          USERNAME: rahul-527
        run: |
          echo "Testing workflow"
